### ISSUE TITLE
E118: Too many arguments for function: <SNR>36_tick                                                                                            

### ISSUE THREAD

**Issue by lesguillemets** [yuttie/comfortable-motion.vim#1]
`<C-f>` など `comfortable_motion#flick` が呼ばれるときに上記エラーが出ます．環境は `vim 8.0.0134` , Huge version (`+timers`)です．

多分 `call timer_start(0, function("s:tick"), {'repeat': 0})` で `tick` に [timer ID が渡される](https://github.com/vim/vim/blob/v8.0.0134/runtime/doc/eval.txt#L7826-L7829) からだと思うのですが，neovim/vim 間で違いがあるのかとかは調べられていません．

**Comment by kamina91** [comment]
@yuttie @lesguillemets 同様の現象が起きています。
環境も全く同じ `8.0.0134 +timers` です。
また、 `NVIM v0.2.0-150-g33319b1` でも同様の問題が起きています。
取り急ぎ報告まで。

**Comment by yuttie** [comment]
報告頂きありがとうございます。調査してみます！

**Comment by yuttie** [comment]
@lesguillemets @kamina91 問題を修正しました。
ご指摘の通り、s:tick()にパラメータを1つ追加することでVim 8でも動作確認できました。

Neovimでは問題無かったので、両者が基本同じだと考えて書いてると罠にはまるという例ですね。
ありがとうございました。快適なスクロールをお楽しみ下さい！

**Comment by lesguillemets** [comment]
こちらこそありがとうございます！ :tada:
