### ISSUE TITLE
Plugin changes position of cursor on screen

### ISSUE THREAD

**Issue by ismay** [yuttie/comfortable-motion.vim#10]
When scrolling (for example with ctrl-d or ctrl-u), this plugin changes the vertical position of the cursor on the screen, but the cursor stays on the same linenumber. 

Whereas when this plugin is not enabled, while scrolling up or down the vertical position of the cursor on the screen stays the same and the linenumber that the cursor is on will change.

Any reason for this difference? I'd prefer the default behaviour, but _with_ the smooth scrolling that this plugin enables.

**Comment by yuttie** [comment]
@ismay Sorry for my late reply.
Currently, this plugin uses `<C-e>` and `<C-y>` to scroll by repeatedly inputting these keys, and so the difference comes from this.

I've just made it possible to change these keys to other combinations like `j` and `k` in `customizable-scroll-keys` branch.  With the branch, you can change keys used for scrolling as follows:
```vim
let g:comfortable_motion_scroll_down_key = "j"
let g:comfortable_motion_scroll_up_key = "k"
```
For example, this configuration makes scrolling as shown below:

![customizable-scroll-keys](https://cloud.githubusercontent.com/assets/158553/24331179/ebc5b106-1269-11e7-90c2-747a68dec44b.gif)

If this makes you happy, I will merge the branch :grinning:

**Comment by ismay** [comment]
> If this makes you happy, I will merge the branch 😀

Yeah definitely! Looks perfect! 👍

**Comment by yuttie** [comment]
@ismay Great!  I've just merged it.
