### ISSUE TITLE
Mouse support?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [yuttie/comfortable-motion.vim#15]

**Comment by yuttie** [comment]
If your Vim/NeoVim has mouse support, you can get mouse wheel to scroll a window by the following settings:
```vim
noremap <silent> <ScrollWheelDown> :call comfortable_motion#flick(40)<CR>
noremap <silent> <ScrollWheelUp>   :call comfortable_motion#flick(-40)<CR>
```

You may need to enable the `mouse` option for the above to work, for example, by `set mouse=a`.

**Comment by yuttie** [comment]
@vitaly-zdanevich I've just added the above descriptions to README.md.
Thanks for your question!
