### ISSUE TITLE
Faster scroll speed?

### ISSUE THREAD

**Issue by CallumHoward** [yuttie/comfortable-motion.vim#8]
Is there a way to set the scroll speed to be faster? For example, 4x as fast.

**Comment by yuttie** [comment]
It might be possible, but it will not be intuitive to configure. You will need trial and error.

If you just need faster speed, you can give `comfortable_motion#flick()` function a value whose absolute value is as large as you like. Try `:call comfortable_motion#flick(1600)`, which means "begin scrolling with four times faster initial speed than the default (default value is 400)".

However, you will notice it scrolls a buffer too much. It's like that a car with higher speed needs longer distance to stop. You will need to configure `g:comfortable_motion_friction` and `g:comfortable_motion_air_drag` appropriately. For example, with the above configuration, you can achieve the same amount of scroll as the default by `:let g:comfortable_motion_air_drag = 24.5` or `:let g:comfortable_motion_friction = 22500.0`. Note that these settings give you different tastes.

Currently, no tools are provided to compute such appropriate parameter values. I think it would be better to provide some graphical configuration tool (maybe on GitHub pages?), but I don't have enough time for now. That said, it's not so difficult to find parameter values manually. I found previous values in one or two minutes :)

**Comment by yuttie** [comment]
I'm closing this issue because there is no active discussion.
Please feel free to re-open this issue, if you need.

**Comment by tuckerconnelly** [comment]
These seem pretty good/fast to me:

```
nnoremap <silent> <C-d> :call comfortable_motion#flick(1600)<CR>
nnoremap <silent> <C-u> :call comfortable_motion#flick(-1600)<CR>

nnoremap <silent> <C-f> :call comfortable_motion#flick(3200)<CR>
nnoremap <silent> <C-b> :call comfortable_motion#flick(-3200)<CR>

let g:comfortable_motion_friction = 16000.0
let g:comfortable_motion_air_drag = 12.0
```

Though, would be nice to be able to configure by distance/time instead of speed/friction/drag (:
